/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package josezuniga_lab8;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenadoContactos();
        llenarCombo();
        colgar.setVisible(false);
        tiempoTrans.setVisible(false);
        tiempolabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdContactos = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        creaContEdad = new javax.swing.JSpinner();
        creaContNombre = new javax.swing.JTextField();
        creaContCorreo = new javax.swing.JTextField();
        creaContDire = new javax.swing.JTextField();
        creaContNumero = new javax.swing.JFormattedTextField();
        creaContCrea = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        modContCorreo = new javax.swing.JTextField();
        modContDire = new javax.swing.JTextField();
        modContNumero = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        modContMod = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        modContEdad = new javax.swing.JSpinner();
        modContNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        modContBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        eliContBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        contEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contTabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jdMensajes = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        mesajetxt = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mensaBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jdLlamadas = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        llamaBox = new javax.swing.JComboBox<>();
        llamar = new javax.swing.JButton();
        colgar = new javax.swing.JButton();
        tiempolabel = new javax.swing.JLabel();
        tiempoTrans = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuContactos = new javax.swing.JMenu();
        menuMensajes = new javax.swing.JMenu();
        menuLlamadas = new javax.swing.JMenu();

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Edad");

        jLabel5.setText("Numero");

        jLabel6.setText("Correo");

        jLabel7.setText("Direccion");

        creaContEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        creaContDire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaContDireActionPerformed(evt);
            }
        });

        creaContNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        creaContCrea.setText("Crear");
        creaContCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaContCreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(creaContCorreo))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(creaContEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(creaContNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(creaContDire, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(creaContNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(creaContCrea)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(creaContNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(creaContEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(creaContNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(creaContCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(creaContDire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(creaContCrea)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Agregar", jPanel1);

        modContDire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modContDireActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre");

        modContMod.setText("Modificar");
        modContMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modContModActionPerformed(evt);
            }
        });

        jLabel9.setText("Edad");

        jLabel10.setText("Numero");

        jLabel11.setText("Correo");

        jLabel12.setText("Direccion");

        modContEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel14.setText("Contacto");

        modContBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modContBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(modContMod))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modContBox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(modContCorreo))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(modContEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(modContNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(modContDire, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(modContNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(modContBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(modContNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(modContEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(modContNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(modContCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(modContDire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(modContMod)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        jLabel13.setText("Contacto");

        contEliminar.setText("Eliminar");
        contEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addComponent(eliContBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(contEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliContBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(78, 78, 78)
                .addComponent(contEliminar)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        contTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Edad", "Correo", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(contTabla);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPanel4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Contactos");

        javax.swing.GroupLayout jdContactosLayout = new javax.swing.GroupLayout(jdContactos.getContentPane());
        jdContactos.getContentPane().setLayout(jdContactosLayout);
        jdContactosLayout.setHorizontalGroup(
            jdContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdContactosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdContactosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jdContactosLayout.setVerticalGroup(
            jdContactosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdContactosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mesajetxt.setColumns(20);
        mesajetxt.setRows(5);
        jScrollPane2.setViewportView(mesajetxt);

        jLabel15.setText("Mensaje:");

        jLabel16.setText("Destinatario:");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdMensajesLayout = new javax.swing.GroupLayout(jdMensajes.getContentPane());
        jdMensajes.getContentPane().setLayout(jdMensajesLayout);
        jdMensajesLayout.setHorizontalGroup(
            jdMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdMensajesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jdMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdMensajesLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(27, 27, 27)
                        .addComponent(mensaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdMensajesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        jdMensajesLayout.setVerticalGroup(
            jdMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdMensajesLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jdMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(mensaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        jLabel17.setText("Contacto");

        llamar.setBackground(new java.awt.Color(0, 255, 0));
        llamar.setText("Llamar");
        llamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llamarActionPerformed(evt);
            }
        });

        colgar.setBackground(new java.awt.Color(255, 0, 0));
        colgar.setText("Colgar");
        colgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colgarActionPerformed(evt);
            }
        });

        tiempolabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tiempolabel.setText("Tiempo:");

        tiempoTrans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tiempoTrans.setText("jLabel19");

        jButton2.setText("Registros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdLlamadasLayout = new javax.swing.GroupLayout(jdLlamadas.getContentPane());
        jdLlamadas.getContentPane().setLayout(jdLlamadasLayout);
        jdLlamadasLayout.setHorizontalGroup(
            jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdLlamadasLayout.createSequentialGroup()
                .addGroup(jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdLlamadasLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colgar)
                            .addComponent(llamar)))
                    .addGroup(jdLlamadasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(jdLlamadasLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdLlamadasLayout.createSequentialGroup()
                                        .addComponent(tiempolabel)
                                        .addGap(70, 70, 70)
                                        .addComponent(tiempoTrans))
                                    .addComponent(llamaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jdLlamadasLayout.setVerticalGroup(
            jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdLlamadasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(llamaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(llamar)
                .addGap(37, 37, 37)
                .addComponent(colgar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jdLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempolabel)
                    .addComponent(tiempoTrans))
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido");

        menuContactos.setText("Contactos");
        menuContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuContactosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuContactos);

        menuMensajes.setText("Mensajes");
        menuMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMensajesMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMensajes);

        menuLlamadas.setText("Llamadas");
        menuLlamadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLlamadasMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLlamadas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuContactosMouseClicked
        jdContactos.pack();
        jdContactos.setLocationRelativeTo(this);
        jdContactos.setVisible(true);
    }//GEN-LAST:event_menuContactosMouseClicked

    private void creaContDireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaContDireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creaContDireActionPerformed

    private void modContDireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modContDireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modContDireActionPerformed

    private void modContModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modContModActionPerformed
        if (modContBox.getSelectedIndex() >= 0) {
            String nombre, correo, direccion;
            int edad, numero;
            nombre = modContNombre.getText();
            correo = modContCorreo.getText();
            direccion = modContDire.getText();
            edad = Integer.parseInt(modContEdad.getValue().toString());
            numero = Integer.parseInt(modContNumero.getText());
            Contactos contact = new Contactos(nombre, correo, direccion, edad, numero);
            contactos.set(modContBox.getSelectedIndex(), contact);
            //llenarcombo
            base.conectar();
            try {
                base.query.execute("UPDATE Contactos  Set NumeroTelefonico = '" + contact.getNumero()  + "',Nombre ="
                        + "'" + contact.getNombre() + "',Correo = '" + contact.getCorreo() + "',Direccion = '" + contact.getDireccion() + "', Edad = '" + contact.getEdad() + "'"
                                + " WHERE NumeroTelefonico = " + "'" + ((Contactos)modContBox.getSelectedItem()).getNumero() + "'");
            } catch (Exception e) {
                e.printStackTrace();
            }
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_modContModActionPerformed

    private void creaContCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaContCreaActionPerformed
        String nombre, correo, direccion;
        int edad, numero;
        nombre = creaContNombre.getText();
        correo = creaContCorreo.getText();
        direccion = creaContDire.getText();
        edad = Integer.parseInt(creaContEdad.getValue().toString());
        numero = Integer.parseInt(creaContNumero.getText());
        Contactos cont = new Contactos(nombre, correo, direccion, edad, numero);
        contactos.add(cont);
        llenarCombo();
        creaContCorreo.setText("");
        creaContDire.setText("");
        creaContEdad.setValue(0);
        creaContNombre.setText("");
        creaContNumero.setText("");
        base.conectar();
        try {
            base.query.execute("INSERT INTO Contactos (NumeroTelefonico,Nombre,Correo,Direccion,Edad) VALUES ('" + cont.getNumero() + "','" + cont.getNombre() + "'"
                    + ",'" + cont.getCorreo() + "','" + cont.getDireccion() + "','" + cont.getEdad() + "')");
            base.commit();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jdContactos, "Error Fatal!");
            e.printStackTrace();
        }
        base.desconectar();
    }//GEN-LAST:event_creaContCreaActionPerformed

    private void modContBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modContBoxItemStateChanged
        if (modContBox.getSelectedIndex() >= 0) {
            System.out.println(modContBox.getSelectedIndex());
            Contactos contact = (Contactos) modContBox.getSelectedItem();
            modContCorreo.setText(contact.getCorreo());
            modContDire.setText(contact.getDireccion());
            modContEdad.setValue(contact.getEdad());
            modContNombre.setText(contact.getNombre());
            modContNumero.setText(String.valueOf(contact.getNumero()));
        }
    }//GEN-LAST:event_modContBoxItemStateChanged

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 1) {
            modContBox.setSelectedIndex(-1);
        } else if (jTabbedPane1.getSelectedIndex() == 3) {
            contTabla.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Numero", "Nombre", "Edad", "Correo", "Direccion"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            DefaultTableModel modelo = (DefaultTableModel) contTabla.getModel();
            for (Contactos contacto : contactos) {
               Object arr[] = new Object[]{contacto.getNumero(), contacto.getNombre(), contacto.getEdad(), contacto.getCorreo(), contacto.getDireccion()};
               modelo.addRow(arr);
            }
            contTabla.setModel(modelo);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (mensaBox.getSelectedIndex() >= 0 && !mesajetxt.getText().equals("")) {
            Mesaje mensaje = new Mesaje("Jose Zuniga", ((Contactos)mensaBox.getSelectedItem()).getNombre(), mesajetxt.getText());
            base.conectar();
            try {
                base.query.execute("INSERT INTO Mensajes (Emisor,Receptor,Mensaje,Fecha) VALUES "
                        + "('" + mensaje.getEmisor() + "','" + mensaje.getReceptor() + "','" + mensaje.getContenido() + "','"
                                + "" + mensaje.getFecha() +"')");
                base.commit();
            } catch (Exception e) {
                e.printStackTrace();
            }
            base.desconectar();
            mesajetxt.setText("");
            mensaBox.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMensajesMouseClicked
        jdMensajes.pack();
        jdMensajes.setLocationRelativeTo(this);
        jdMensajes.setVisible(true);
    }//GEN-LAST:event_menuMensajesMouseClicked

    private void menuLlamadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLlamadasMouseClicked
        jdLlamadas.pack();
        jdLlamadas.setLocationRelativeTo(this);
        jdLlamadas.setVisible(true);
    }//GEN-LAST:event_menuLlamadasMouseClicked

    private void llamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llamarActionPerformed
        if (llamaBox.getSelectedIndex() >= 0) {
            llamar.setEnabled(false);
            colgar.setVisible(true);
            tiempoTrans.setVisible(true);
            tiempolabel.setVisible(true);
            Llamadas llamada = new Llamadas("", "Jose Zuniga", ((Contactos)llamaBox.getSelectedItem()).getNombre());
            hilo = new HiloLlamada(tiempoTrans, new Date());
            hilo.setLlamada(llamada);
            proceso1 = new Thread(hilo);
            proceso1.start();
            llamar.setEnabled(false);
        }
    }//GEN-LAST:event_llamarActionPerformed

    private void colgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colgarActionPerformed
        hilo.setVive(false);
        llamar.setEnabled(true);
        jTextArea1.append(hilo.getLlamada().toString());
    }//GEN-LAST:event_colgarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog1.pack();
        jDialog1.setLocationRelativeTo(jdLlamadas);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void contEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contEliminarActionPerformed
        if (eliContBox.getSelectedIndex() >= 0) {
            contactos.remove(eliContBox.getSelectedIndex());
            base.conectar();
            try {
                base.query.execute("DELTE FROM Contactos where NumeroTelefonico = '" + ((Contactos)eliContBox.getSelectedItem()).getNumero() + "'");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_contEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void llenadoContactos() {
        contactos = new ArrayList<>();
        base.conectar();
        try {
            base.query.execute("select * from Contactos");
            ResultSet rs = base.query.getResultSet();
            while (rs.next()) {
                Contactos cont = new Contactos(rs.getString("Nombre"), rs.getString("Correo"), rs.getString("Direccion"), rs.getInt("Edad"), rs.getInt("NumeroTelefonico"));
                contactos.add(cont);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        base.desconectar();

    }

    public void llenarCombo(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Contactos contacto : contactos) {
            modelo.addElement(contacto);
        }
        modContBox.setModel(modelo);
        eliContBox.setModel(modelo);
        mensaBox.setModel(modelo);
        llamaBox.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colgar;
    private javax.swing.JButton contEliminar;
    private javax.swing.JTable contTabla;
    private javax.swing.JTextField creaContCorreo;
    private javax.swing.JButton creaContCrea;
    private javax.swing.JTextField creaContDire;
    private javax.swing.JSpinner creaContEdad;
    private javax.swing.JTextField creaContNombre;
    private javax.swing.JFormattedTextField creaContNumero;
    private javax.swing.JComboBox<String> eliContBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog jdContactos;
    private javax.swing.JDialog jdLlamadas;
    private javax.swing.JDialog jdMensajes;
    private javax.swing.JComboBox<String> llamaBox;
    private javax.swing.JButton llamar;
    private javax.swing.JComboBox<String> mensaBox;
    private javax.swing.JMenu menuContactos;
    private javax.swing.JMenu menuLlamadas;
    private javax.swing.JMenu menuMensajes;
    private javax.swing.JTextArea mesajetxt;
    private javax.swing.JComboBox<String> modContBox;
    private javax.swing.JTextField modContCorreo;
    private javax.swing.JTextField modContDire;
    private javax.swing.JSpinner modContEdad;
    private javax.swing.JButton modContMod;
    private javax.swing.JTextField modContNombre;
    private javax.swing.JFormattedTextField modContNumero;
    private javax.swing.JLabel tiempoTrans;
    private javax.swing.JLabel tiempolabel;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Contactos> contactos = new ArrayList<>();
    private Dba base = new Dba("./Lab8.mdb");
    HiloLlamada hilo = new HiloLlamada(tiempoTrans, new Date());
     Thread proceso1;
}
